- name: Install nautilus, blueberry and arandr
  become: yes
  package:
    name: "{{ item }}"
    state: present
  loop:
    - nautilus
    - blueberry
    - arandr
- name: Install better CLI tools
  become: yes
  package:
    name: "{{ item }}"
    state: present
  loop:
    - bat
    - exa
    - duf
    - fx
- name: Copy personal aliases
  copy:
    src: aliases-mark
    dest: ~/.pqrs/bashrc.d/aliases-mark
- name: Copy dir_colors file
  copy:
    src: dir_colors
    dest: ~/.pqrs/dir_colors
- name: Link dir_colors file
  file:
    src: ~/.pqrs/dir_colors
    dest: ~/.dir_colors
    state: link
    force: yes
- name: Install fancy screenfetch
  become: yes
  package:
    name: screenfetch
    state: present
- name: Clone pipes.sh repo
  git:
    repo: git@github.com:pipeseroni/pipes.sh.git
    dest: ~/Installed/pipes.sh
    version: master
- name: Install pipes.sh
  become: yes
  command:
    chdir: "{{ home }}/Installed/pipes.sh"
    cmd: make install
- name: Install asciiMol viewer
  become: yes
  pip:
    executable: /usr/bin/pip3
    name: asciimol
    state: present
- name: Download mmterm viewer
  git:
    repo: git@github.com:jgreener64/mmterm.git
    dest: ~/Installed/mmterm
    version: master
  when: role_version is version("0.1.13", "lt")
- name: Install mmterm
  become: yes
  command:
    chdir: "{{ home }}/Installed/mmterm"
    cmd: /usr/bin/pip3 install -e .
  when: role_version is version("0.1.13", "lt")
