- name: Install nautilus, blueberry and arandr
  become: yes
  package:
    name: "{{ item }}"
    state: present
  loop:
    - nautilus
    - blueberry
    - arandr
- name: Install better CLI tools
  become: yes
  package:
    name: "{{ item }}"
    state: present
  loop:
    - bat
    - exa
    - duf
    - fx
- name: Copy personal aliases
  copy:
    src: aliases-mark
    dest: ~/.pqrs/bashrc.d/aliases-mark
- name: Copy dir_colors file
  copy:
    src: dir_colors
    dest: ~/.pqrs/dir_colors
- name: Link dir_colors file
  file:
    src: ~/.pqrs/dir_colors
    dest: ~/.dir_colors
    state: link
    force: yes
- name: Install fancy screenfetch
  become: yes
  package:
    name: screenfetch
    state: present
