- name: Install nautilus, blueman, pavucontrol and arandr
  become: yes
  package:
    name: "{{ item }}"
    state: present
  loop:
    - nautilus
    - blueman
    - pavucontrol
    - arandr
  when: role_version is version("0.1.13", "lt")
- name: Install better CLI tools
  become: yes
  package:
    name: "{{ item }}"
    state: present
  loop:
    - bat
    - exa
    - duf
  when: role_version is version("0.1.13", "lt")
- name: Install fx via snap
  become: yes
  command: snap install fx -y
  when: role_version is version("0.1.13", "lt")
- name: Copy personal aliases
  copy:
    src: aliases-mark
    dest: ~/.pqrs/bashrc.d/aliases-mark
  when: role_version is version("0.1.19", "lt")
- name: Copy dir_colors file
  copy:
    src: dir_colors
    dest: ~/.pqrs/dir_colors
  when: role_version is version("0.1.13", "lt")
- name: Link dir_colors file
  file:
    src: ~/.pqrs/dir_colors
    dest: ~/.dir_colors
    state: link
    force: yes
  when: role_version is version("0.1.13", "lt")
- name: Install fancy neofetch
  become: yes
  package:
    name: neofetch
    state: present
  when: role_version is version("0.1.15", "lt")
- name: Clone pipes.sh repo
  git:
    repo: git@github.com:pipeseroni/pipes.sh.git
    dest: ~/Installed/pipes.sh
    version: master
  when: role_version is version("0.1.13", "lt")
- name: Install pipes.sh
  become: yes
  command:
    chdir: "{{ home }}/Installed/pipes.sh"
    cmd: make install
  when: role_version is version("0.1.13", "lt")
- name: Install asciiMol viewer
  become: yes
  pip:
    executable: /usr/bin/pip3
    name: asciimol
    state: present
  when: role_version is version("0.1.13", "lt")
- name: Download mmterm viewer
  git:
    repo: git@github.com:jgreener64/mmterm.git
    dest: ~/Installed/mmterm
    version: master
  when: role_version is version("0.1.13", "lt")
- name: Install mmterm
  become: yes
  command:
    chdir: "{{ home }}/Installed/mmterm"
    cmd: /usr/bin/pip3 install -e .
  when: role_version is version("0.1.13", "lt")
- name: Install starship
  become: yes
  package:
    name: starship
    state: present
  when: role_version is version("0.1.14", "lt")
- name: Copy starship config
  copy:
    src: starship.toml
    dest: ~/.pqrs/starship.toml
  when: role_version is version("0.1.14", "lt")
- name: Link starship.toml file
  file:
    src: ~/.pqrs/starship.toml
    dest: ~/.config/starship.toml
    state: link
    force: yes
  when: role_version is version("0.1.14", "lt")
- name: It's raining top's
  become: yes
  package:
    name: "{{ item }}"
    state: present
  loop:
    - iotop
    - bpytop
    - iftop
  when: role_version is version("0.1.16", "lt")
- name: Downloading ctop (container monitoring)
  become: yes
  command:
    cmd: "sudo wget https://github.com/bcicen/ctop/releases/download/0.7.6/ctop-0.7.6-linux-amd64 -O /usr/local/bin/ctop"
  when: role_version is version("0.1.16", "lt")
- name: Making ctop executable
  become: yes
  file:
    dest: /usr/local/bin/ctop
    mode: +x
  when: role_version is version("0.1.16", "lt")
- name: Download gotop
  command:
    chdir: ~/Installed
    cmd: wget https://github.com/xxxserxxx/gotop/releases/download/v4.1.3/gotop_v4.1.3_linux_amd64.rpm
  when: role_version is version("0.1.17", "lt")
- name: Install gotop
  become: yes
  command:
    chdir: "{{ home }}/Installed"
    cmd: sudo dnf install gotop_v4.1.3_linux_amd64.rpm -y
  when: role_version is version("0.1.17", "lt")
- name: Install perl (for fetch-master 6000)
  become: yes
  package:
    name: perl
    state: present
  when: role_version is version("0.1.18", "lt")
- name: Download fetch-master 6000
  command:
    chdir: ~/Installed
    cmd: "wget https://raw.githubusercontent.com/anhsirk0/fetch-master-6000/master/fm6000.pl -O fm6000"
  when: role_version is version("0.1.18", "lt")
- name: Install fetch-master 6000
  copy:
    src: ~/Installed/fm6000
    dest: ~/.local/bin
    mode: +x
  when: role_version is version("0.1.18", "lt")
