- name: Install nautilus for file management
  become: yes
  package:
      name: "{{ item }}"
      state: present
  loop:
    - nautilus
    - blueberry
    - arandr
- name: Copy personal aliases
  copy:
    src: aliases-mark
    dest: ~/.pqrs/bashrc.d/aliases-mark
