- name: Install nautilus, blueberry and arandr
  become: yes
  package:
      name: "{{ item }}"
      state: present
  loop:
    - nautilus
    - blueberry
    - arandr
- name: Install better CLI tools
  become: yes
  package:
      name: "{{ item }}"
      state: present
  loop:
    - bat
    - exa
    - duf
    - fx
- name: Copy personal aliases
  copy:
    src: aliases-mark
    dest: ~/.pqrs/bashrc.d/aliases-mark
