#!/usr/bin/env bash
KCONTEXT=$(kubectl config current-context 2>/dev/null)
if [[ $?=="0" ]]; then
    CC=$(kubectl config view -ojsonpath='{..current-context}')
    KNAMESPACE=$(kubectl config view -o json | jq ".contexts[0] .context .namespace" | tr -d '"')
    echo "<span font=\"Font Awesome 5 Free Solid 14\">☸</span> $KCONTEXT/$KNAMESPACE <span font=\"Font Awesome 5 Free Solid 14\">☸</span>"
    echo "<span font=\"Font Awesome 5 Free Solid 14\">☸</span> $KCONTEXT/$KNAMESPACE <span font=\"Font Awesome 5 Free Solid 14\">☸</span>"

    #echo \#00ffaf # color
    #echo \#000000 # background
    #echo \#00ffaf # border
fi
