#!/usr/bin/env bash
# Copyright (C) 2014 Alexander Keller <github@nycroth.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#------------------------------------------------------------------------
if [[ -z "$INTERFACE" ]] ; then
    INTERFACE="${BLOCK_INSTANCE:-wlp9s0}"
fi
#------------------------------------------------------------------------

COLOR_GE80=${COLOR_GE80:-#a3be8c}
COLOR_GE60=${COLOR_GE60:-#ebcb8b}
COLOR_GE40=${COLOR_GE40:-#b48ead}
COLOR_LOWR=${COLOR_LOWR:-#d08770}
COLOR_DOWN=${COLOR_DOWN:-#bf616a}

# As per #36 -- It is transparent: e.g. if the machine has no battery or wireless
# connection (think desktop), the corresponding block should not be displayed.
[[ ! -d /sys/class/net/${INTERFACE}/wireless ]] && exit

# If the wifi interface exists but no connection is active, "down" shall be displayed.
if [[ "$(cat /sys/class/net/$INTERFACE/operstate)" = 'down' ]]; then
    echo "down"
    echo "down"
    echo $COLOR_DOWN  # color
    echo \#000000  # background
    echo $COLOR_DOWN  # border
    exit
fi

#------------------------------------------------------------------------

QUALITY=$(iw dev ${INTERFACE} link | grep 'dBm$' | grep -Eoe '-[0-9]{2}' | awk '{print  ($1 > -50 ? 100 :($1 < -100 ? 0 : ($1+100)*2))}')

#------------------------------------------------------------------------

echo "${QUALITY}%" # full text
echo "${QUALITY}%" # short text


# color
if [[ $QUALITY -ge 80 ]]; then
    echo $COLOR_GE80
elif [[ $QUALITY -ge 60 ]]; then
    echo $COLOR_GE60
elif [[ $QUALITY -ge 40 ]]; then
    echo $COLOR_GE40
else
    echo $COLOR_LOWR
fi

# background
#echo \#000000

# border
#if [[ $QUALITY -ge 80 ]]; then
#    echo $COLOR_GE80
#elif [[ $QUALITY -ge 60 ]]; then
#    echo $COLOR_GE60
#elif [[ $QUALITY -ge 40 ]]; then
#    echo $COLOR_GE40
#else
#    echo $COLOR_LOWR
#fi
