- name: Copy i3 config file
  copy:
    src: i3-config
    dest: ~/.pqrs/i3-config
- name: Uninstall vanilla i3 to enable i3-gaps
  become: yes
  package:
    name: i3
    state: absent
- name: Install i3-gaps for gaps between windows
  become: yes
  package:
    name: i3-gaps
    state: present
- name: Add community Copr for i3blocks-contrib
  become: yes
  command:
    cmd: dnf copr enable -y skidnik/i3blocks
    creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:skidnik:i3blocks.repo
- name: Install i3blocks for info blocks in status bars
  become: yes
  package:
    name: "{{ item }}"
    state: present
  loop:
    - i3blocks
    - i3blocks-contrib
- name: Install dependencies for my personal i3blocks
  become: yes
  package:
    name: "{{ item }}"
    state: present
  loop:
    - kbdd
    - acpi
- name: Add community Copr for i3lock-color
  become: yes
  command:
    cmd: dnf copr enable -y tokariew/i3lock-color
    creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:tokariew:i3lock-color.repo
- name: Install betterlockscreen dependencies
  become: yes
  package:
    name: "{{ item }}"
    state: present
  loop:
    - xset
    - i3lock-color
    - ImageMagick
    - xdpyinfo
    - xrandr
    - xrdb
    - autoconf
    - automake
    - cairo-devel
    - fontconfig
    - gcc
    - libev-devel
    - libjpeg-turbo-devel
    - libXinerama
    - libxkbcommon-devel
    - libxkbcommon-x11-devel
    - libXrandr
    - pam-devel
    - pkgconf
    - xcb-util-image-devel
    - xcb-util-xrm-devel
- name: Install fontawesome for status bar icons
  become: yes
  package:
    name: "{{ item }}"
    state: present
  loop:
    - fontawesome-fonts
    - fontawesome5-fonts-all
- name: Download betterlockscreen
  become: yes
  command:
    chdir: "{{ home }}/Installed/"
    cmd: "{{ item }}"
    creates: "{{ home }}/Installed/betterlockscreen-main"
  loop:
    - wget https://github.com/pavanjadhaw/betterlockscreen/archive/refs/heads/main.zip
    - unzip main.zip
    - rm main.zip
- name: Install betterlockscreen
  become: yes
  command:
    chdir: "{{ home }}/Installed/betterlockscreen-main"
    cmd: "{{ item }}"
  loop:
    - chmod u+x betterlockscreen
    - cp betterlockscreen /usr/local/bin/
    - cp system/betterlockscreen@.service /usr/lib/systemd/system/
    - systemctl enable betterlockscreen@$USER
- name: Clone nerd-fonts repo
  git:
    repo: https://github.com/ryanoasis/nerd-fonts
    dest: ~/Installed/nerd-fonts
    version: master
- name: Install nerd-fonts
  become: yes
  command:
    chdir: "{{ home }}/Installed/nerd-fonts"
    cmd: ./install.sh
- name: Copy i3blocks config files
  copy:
    src: "{{ item }}"
    dest: "~/.pqrs/{{ item }}"
  loop:
    - i3blocks-top.conf
    - i3blocks-bottom.conf
    - i3blocks.d/
- name: Install packages to scale and beautify i3
  become: yes
  package:
    name: lxappearance
    state: present
- name: Copy X config files
  copy:
    src: "{{ item }}"
    dest: "~/{{ item }}"
  loop:
    - .xinitrc
    - .Xresources
- name: Copy icon packages
  copy:
    src: "{{ item }}"
    dest: "~/.icons/{{ item }}"
  loop:
    - candy-icons.zip
    - sovtc_icons.zip
- name: Installing candy-icons
  command:
    chdir: ~/.icons
    cmd: "{{ item }}"
    creates: ~/.icons/candy-icons
  loop:
    - unzip candy-icons.zip
    - rm candy-icons.zip
- name: Installing sovtc-icons
  command:
    chdir: ~/.icons
    cmd: "{{ item }}"
    creates: ~/.icons/sovtc_icons
  loop:
    - unzip sovtc_icons.zip
    - rm sovtc_icons.zip
- name: Copy themes packages
  copy:
    src: "{{ item }}"
    dest: "~/.themes/{{ item }}"
  loop:
    - cyberhack.zip
    - Ultimate-Plata-Dark.zip
- name: Installing themes packages
  command:
    chdir: ~/.themes
    cmd: "{{ item }}"
    creates: ~/.themes/cyberhack
  loop:
    - unzip cyberhack.zip
    - rm cyberhack.zip
- name: Installing themes packages
  command:
    cmd: "{{ item }}"
    chdir: ~/.themes
    creates: ~/.themes/Ultimate-Plata-Dark
  loop:
    - unzip Ultimate-Plata-Dark.zip
    - rm Ultimate-Plata-Dark.zip
- name: Install dunst and compton
  become: yes
  package:
    name: "{{ item }}"
    state: present
  loop:
    - dunst
    - compton
- name: Copy dunstrc file
  copy:
    src: dunstrc
    dest: ~/.pqrs/dunstrc
- name: Copy compton.conf file
  copy:
    src: compton.conf
    dest: ~/.pqrs/compton.conf
